version: "3"
services:
  app:
    container_name: production-api-and-annotator
    restart: always
    build: .
    ports:
      - "80:80"
    links:
      - mongo
    volumes:
      - "./tatorte_classifier:/tatorte_classifier"
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
