version: "3"
services:
  app:
    container_name: production-api-and-annotator
    restart: always
    build: .
    ports:
      - "5000:5000"
    links:
      - mongo
    volumes:
      - "./tatorte_classifier:/app/tatorte_classifier"
      - "./configuration.py:/app/configuration.py"
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
