version: "3"
services:
  app:
    container_name: production-api-and-annotator
    restart: always
    build: .
    ports:
      - "5000:5000"
    links:
      - mongo
    volumes:
      - "/home/peer/Code/AI/praktikum/tatorte-classifier-sharing/app:/app"
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
